### ISSUE TITLE
panic: runtime error: index out of range [14] with length 14

### ISSUE THREAD

**Issue by lucgerrits** [subscan-explorer/subscan-essentials#216] opened 2023-02-22 15:21 UTC
Hi,
When running the docker compose files, I've always this error:
```
subscan-essentials-subscan-api-1       | 2023/02/22 15:10:19 start watch filepath: ../configs
subscan-essentials-subscan-api-1       | panic: runtime error: index out of range [14] with length 14
subscan-essentials-subscan-api-1       |        panic: runtime error: invalid memory address or nil pointer dereference
subscan-essentials-subscan-api-1       | [signal SIGSEGV: segmentation violation code=0x1 addr=0xd8 pc=0x89afd0]
subscan-essentials-subscan-api-1       | 
subscan-essentials-subscan-api-1       | goroutine 1 [running]:
subscan-essentials-subscan-api-1       | github.com/itering/scale%2ego.(*MetadataDecoder).CheckRegistry(0x0, 0x25e8, 0x27e8, 0x0)
subscan-essentials-subscan-api-1       |        /go/pkg/mod/github.com/itering/scale.go@v1.0.51/metadata.go:43 +0x50
subscan-essentials-subscan-api-1       | github.com/itering/subscan/internal/service.(*Service).initSubRuntimeLatest.func1(0xc0004b04c0)
subscan-essentials-subscan-api-1       |        /subscan/internal/service/service.go:42 +0x70
subscan-essentials-subscan-api-1       | panic(0xbec260, 0xc0002fb680)
subscan-essentials-subscan-api-1       |        /usr/local/go/src/runtime/panic.go:969 +0x166
subscan-essentials-subscan-api-1       | github.com/itering/scale.go/types.(*Enum).Process(0xc0000b74a0)
subscan-essentials-subscan-api-1       |        /go/pkg/mod/github.com/itering/scale.go@v1.0.51/types/types.go:317 +0x6c3
subscan-essentials-subscan-api-1       | reflect.Value.call(0xbd8cc0, 0xc0000b74a0, 0xe13, 0xc3fc7c, 0x4, 0x0, 0x0, 0x0, 0xd7d9a0, 0xc0006f8ea0, ...)
subscan-essentials-subscan-api-1       |        /usr/local/go/src/reflect/value.go:460 +0x8ab
subscan-essentials-subscan-api-1       | reflect.Value.Call(0xbd8cc0, 0xc0000b74a0, 0xe13, 0x0, 0x0, 0x0, 0xc0000b74a0, 0xe13, 0x0)
subscan-essentials-subscan-api-1       |        /usr/local/go/src/reflect/value.go:321 +0xb4
subscan-essentials-subscan-api-1       | github.com/itering/scale.go/types.(*ScaleDecoder).ProcessAndUpdateData(0xc00037e3c0, 0xc49474, 0xf, 0x2, 0xc00027133a)
subscan-essentials-subscan-api-1       |        /go/pkg/mod/github.com/itering/scale.go@v1.0.51/types/base.go:140 +0x460
subscan-essentials-subscan-api-1       | github.com/itering/scale%2ego.(*MetadataDecoder).Process(0xc00037e3c0, 0xc000310000, 0xa893)
subscan-essentials-subscan-api-1       |        /go/pkg/mod/github.com/itering/scale.go@v1.0.51/metadata.go:26 +0x18d
subscan-essentials-subscan-api-1       | github.com/itering/substrate-api-rpc/metadata.Latest(0xc00024ba78, 0xc3f2cb)
subscan-essentials-subscan-api-1       |        /go/pkg/mod/github.com/itering/substrate-api-rpc@v0.4.0/metadata/metadata.go:32 +0xb4
subscan-essentials-subscan-api-1       | github.com/itering/subscan/internal/service.(*Service).initSubRuntimeLatest(0xc0004b04c0)
subscan-essentials-subscan-api-1       |        /subscan/internal/service/service.go:59 +0x114
subscan-essentials-subscan-api-1       | github.com/itering/subscan/internal/service.New(0x80)
subscan-essentials-subscan-api-1       |        /subscan/internal/service/service.go:26 +0xa1
subscan-essentials-subscan-api-1       | main.run()
subscan-essentials-subscan-api-1       |        /subscan/cmd/main.go:82 +0x34
subscan-essentials-subscan-api-1       | main.setupApp.func1(0xc00042a000, 0x0, 0x0)
subscan-essentials-subscan-api-1       |        /subscan/cmd/main.go:37 +0x20
subscan-essentials-subscan-api-1       | github.com/urfave/cli.HandleAction(0xb47ec0, 0xc8a268, 0xc00042a000, 0xc000400180, 0x0)
subscan-essentials-subscan-api-1       |        /go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xc8
subscan-essentials-subscan-api-1       | github.com/urfave/cli.(*App).Run(0xc00041e000, 0xc0000201e0, 0x1, 0x1, 0x0, 0x0)
subscan-essentials-subscan-api-1       |        /go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:264 +0x5dd
subscan-essentials-subscan-api-1       | main.main()
subscan-essentials-subscan-api-1       |        /subscan/cmd/main.go:26 +0x71
subscan-essentials-subscan-api-1 exited with code 2
```

> On v0.1.0 (**but I've the same error on master branch**)

**Comment by freehere107** [comment] 2023-02-23 01:46
@lucgerrits It may be caused by the old version of scale.go, I have updated to the latest version, you can try again

**Comment by freehere107** [comment] 2023-02-28 01:05
Since there has been no reply for a long time, I will close this issue. If you have any questions, you can open it again.

**Closed** 2023-02-28 01:05 UTC
